<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="5" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-09-12T17:50:14 IST" name="Suite" finished-at="2023-09-12T17:50:30 IST" duration-ms="15848">
    <groups>
      <group name="purchase">
        <method signature="StandAloneTest.SubmitOrder(java.util.HashMap)[pri:0, instance:TestSuit.StandAloneTest@1bd4fdd]" name="SubmitOrder" class="TestSuit.StandAloneTest"/>
      </group> <!-- purchase -->
    </groups>
    <test started-at="2023-09-12T17:50:14 IST" name="Standalone test" finished-at="2023-09-12T17:50:24 IST" duration-ms="10265">
      <class name="TestSuit.StandAloneTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:TestSuit.StandAloneTest@1bd4fdd]" started-at="2023-09-12T17:50:14 IST" name="launchApplication" finished-at="2023-09-12T17:50:17 IST" duration-ms="3130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:TestSuit.StandAloneTest@1bd4fdd]" started-at="2023-09-12T17:50:17 IST" name="SubmitOrder" data-provider="getData" finished-at="2023-09-12T17:50:20 IST" duration-ms="2735" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Rahul@94, ProductName=ZARA COAT 3, email=rahulkhot94@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:TestSuit.StandAloneTest@1bd4fdd]" started-at="2023-09-12T17:50:20 IST" name="TearDown" finished-at="2023-09-12T17:50:20 IST" duration-ms="130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:TestSuit.StandAloneTest@1bd4fdd]" started-at="2023-09-12T17:50:20 IST" name="launchApplication" finished-at="2023-09-12T17:50:21 IST" duration-ms="1455" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:TestSuit.StandAloneTest@1bd4fdd]" started-at="2023-09-12T17:50:21 IST" name="SubmitOrder" data-provider="getData" finished-at="2023-09-12T17:50:24 IST" duration-ms="2672" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Varad@123, ProductName=ADIDAS ORIGINAL, email=varadkhot@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:TestSuit.StandAloneTest@1bd4fdd]" started-at="2023-09-12T17:50:24 IST" name="TearDown" finished-at="2023-09-12T17:50:24 IST" duration-ms="94" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- TestSuit.StandAloneTest -->
    </test> <!-- Standalone test -->
    <test started-at="2023-09-12T17:50:24 IST" name="Error validation test" finished-at="2023-09-12T17:50:30 IST" duration-ms="5521">
      <class name="TestSuit.ErrorValidations">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:TestSuit.ErrorValidations@22ff4249]" started-at="2023-09-12T17:50:24 IST" name="launchApplication" finished-at="2023-09-12T17:50:25 IST" duration-ms="1441" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder()[pri:0, instance:TestSuit.ErrorValidations@22ff4249]" started-at="2023-09-12T17:50:25 IST" name="SubmitOrder" finished-at="2023-09-12T17:50:26 IST" duration-ms="373" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:TestSuit.ErrorValidations@22ff4249]" started-at="2023-09-12T17:50:26 IST" name="TearDown" finished-at="2023-09-12T17:50:26 IST" duration-ms="96" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:TestSuit.ErrorValidations@22ff4249]" started-at="2023-09-12T17:50:26 IST" name="launchApplication" finished-at="2023-09-12T17:50:28 IST" duration-ms="1577" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:TestSuit.ErrorValidations@22ff4249]" started-at="2023-09-12T17:50:28 IST" name="productErrorValidation" finished-at="2023-09-12T17:50:29 IST" duration-ms="1895" status="FAIL">
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertFalse(Assert.java:34)
at junit.framework.Assert.assertFalse(Assert.java:41)
at TestSuit.ErrorValidations.productErrorValidation(ErrorValidations.java:54)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:TestSuit.ErrorValidations@22ff4249]" started-at="2023-09-12T17:50:29 IST" name="TearDown" finished-at="2023-09-12T17:50:30 IST" duration-ms="128" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- TestSuit.ErrorValidations -->
    </test> <!-- Error validation test -->
  </suite> <!-- Suite -->
</testng-results>
